### PR TITLE
Added functionality to load and run a trained model in CartPole environment

### PR DESCRIPTION
**Pull request by Yonom1**
Dear NotFish232,  

I am a beginner, and after some effort, I finally figured out how to create a pull request on GitHub. I’m now submitting my code to you, though I’m not sure if I’m doing it correctly.  

Also, looking back at the code I wrote yesterday, I realize it was essentially just copying your DQN model, using the `load()` function to load a `.pt` file, and then running the results with the preconfigured environment from Gymnasium. It’s very rough and far from elegant—I apologize if it seems amateurish. In contrast, your code is incredibly well-written. I tried many CartPole tutorial codes from the internet, but none of them worked on my computer. Yours, however, runs perfectly. Thank you so much for sharing it!  

I hope that as I improve my skills in the future, I’ll have more opportunities to exchange ideas with you.  

Best regards,  
Yonom1

### CODE REVIEW

**Comment by NotFish232** [comment]
Hi Yonom1,

I'm glad my code was of some use to you :) 

I think your code looks mainly good, I just have a couple of small suggestions.

- I was thinking instead of having two different files we could keep everything in one file, that way we could share all of the stuff that is identical between training and evaluating, like the DQN model itself. Possibly just have a variable in the file that controls whether the model should be trained or evaluated.
- If we are evaluating the model we want to select actions purely greedily so epsilon should be 0. Having a non-zero epsilon is only for training in order to explore the entire action-space. 
- If possible I would love for the comments to be in English, although I'd understand if you can't do that.

Once again great job with the code! I know from experience how hard it is starting off with Github, but this pull request looks great. If you would like to talk about any other machine learning related topics in the future I would be happy to.

Best,
Notfish232

**Comment by Yonom1** [comment]
> Hi Yonom1,
> 
> I'm glad my code was of some use to you :)
> 
> I think your code looks mainly good, I just have a couple of small suggestions.
> 
> * I was thinking instead of having two different files we could keep everything in one file, that way we could share all of the stuff that is identical between training and evaluating, like the DQN model itself. Possibly just have a variable in the file that controls whether the model should be trained or evaluated.
> * If we are evaluating the model we want to select actions purely greedily so epsilon should be 0. Having a non-zero epsilon is only for training in order to explore the entire action-space.
> * If possible I would love for the comments to be in English, although I'd understand if you can't do that.
> 
> Once again great job with the code! I know from experience how hard it is starting off with Github, but this pull request looks great. If you would like to talk about any other machine learning related topics in the future I would be happy to.
> 
> Best, Notfish232

Dear NotFish232,

I hope this email finds you well.

I wanted to update you on my recent work. I've been refining my implementation of DQN for the CartPole-v1 environment. Recently, I combined the training and evaluation code into a single file to streamline the process. During evaluation, I set epsilon to 0 to ensure a purely greedy strategy for action selection, as you suggested.

Additionally, I’ve made sure to update the comments in my code to English, as you recommended, for better readability and understanding.

Thanks again for your valuable suggestions. They have been incredibly helpful in improving my approach, and I am seeing positive results from the changes. I look forward to any further advice or feedback you may have.

Best regards,
Yomom1

**Comment by NotFish232** [comment]
Hi thanks for making the changes! Could you please delete the other test file now that you put everything into the main one and also make the select_action one a little more clear, i.e. there is no point checking if .random() > 0, during test, just return the model prediction directly. Thanks!

**Comment by Yonom1** [comment]
> Hi thanks for making the changes! Could you please delete the other test file now that you put everything into the main one and also make the select_action one a little more clear, i.e. there is no point checking if .random() > 0, during test, just return the model prediction directly. Thanks!

Hello NotFish232,

I roughly understand your point and have made corresponding adjustments to the project structure and the code in the files. I hope this submission aligns with your tone!

Thank you for the guidance!

Best regards,
Yonom1

**Comment by NotFish232** [comment]
Nicely done. Sorry one last thing, could you squash all the commits down into one commit and then it looks good to merge. Thanks!

**Comment by Yonom1** [comment]
> Nicely done. Sorry one last thing, could you squash all the commits down into one commit and then it looks good to merge. Thanks!

Hello, NotFish232,

After a lot of effort, I finally figured out how to combine all the previous commits into one.

I’ve merged my 5 commits into 1, and I haven’t made any changes to your 4 previous commits.

I hope this meets your expectations.

Best regards,
Yonom1

**Comment by NotFish232** [comment]
Looks good to me! Thanks for the change.

**Pull request merged**
